version: '3.3'

services:
  buildbot:
    build:
      context: ../../
      dockerfile: docker/armhf-buildenv/Dockerfile
    volumes:
      - type: bind
        source: ./target
        target: /femtomail/target
